name: CMake

on:
  push:
    branches: [ "2023_update" ]
  pull_request:
    branches: [ "2023_update" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latests]
        preset: [ci-windows, ci-ubuntu, ci-macos]
        artifact-name: [Windows, Ubuntu, MacOS]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} --preset ${{ matrix.preset }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --preset ${{ matrix.preset }}
      
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: ${{ github.workspace }}\build\Release\
